name: HLS to Repo Splitter (Cookie Method)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک اصلی صفحه ویدیو (URL مرورگر)'
        required: true

permissions:
  contents: write

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yt-dlp, FFMPEG & 7zip
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt-get update && sudo apt-get install -y ffmpeg p7zip-full

      - name: Download and Merge Video
        env:
          # فراخوانی کوکی ذخیره شده در تنظیمات گیت‌هاب
          COOKIES_TXT: ${{ secrets.PH_COOKIES }}
        run: |
          # تبدیل کوکی به یک فایل متنی در سرور
          echo "$COOKIES_TXT" > cookies.txt
          
          # دانلود ویدیو با استفاده از کوکی‌ها برای عبور از فیلتر سایت مبدأ
          yt-dlp --cookies cookies.txt -f "bestvideo[height<=480]+bestaudio/best" --merge-output-format mp4 -o "video_final.mp4" "${{ github.event.inputs.url }}"

      - name: Split and Prepare Files (Instant Mode)
        run: |
          FOLDER_NAME="downloads/video-${{ github.run_id }}"
          mkdir -p "$FOLDER_NAME"
          
          # تکه‌تکه کردن سریع ویدیو به پارت‌های 90 مگابایتی
          7z a -mx=0 -v90m "$FOLDER_NAME/video.7z" video_final.mp4
          
          # پاک‌سازی فایل‌های اضافی و فایل کوکی برای حفظ امنیت
          rm video_final.mp4
          rm -f cookies.txt

      - name: Commit and Push to GitHub Code
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/
          git commit -m "Upload video parts for run ${{ github.run_id }}"
          git push
